# Generated by Django 3.2.25 on 2025-02-18 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balancete',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('data_entrada', models.DateField(auto_now_add=True)),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('versao', models.IntegerField()),
            ],
            options={
                'db_table': 'balancete',
            },
        ),
        migrations.CreateModel(
            name='BaseCalculoPisCofins',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('soma_receita_balancete', models.FloatField()),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('ano', models.IntegerField(default=0)),
                ('mes', models.IntegerField(default=0)),
                ('pis_retido', models.FloatField(default=0)),
                ('compensacao_pis', models.FloatField(default=0)),
                ('pis_recolher', models.FloatField()),
                ('pis_check', models.FloatField()),
                ('pis_darf', models.FloatField()),
                ('pis_dif_darf_recolher', models.FloatField()),
                ('pis_contabilizar', models.FloatField()),
                ('pis', models.FloatField()),
                ('cofins_retido', models.FloatField(default=0)),
                ('compensacao_cofins', models.FloatField(default=0)),
                ('cofins_recolher', models.FloatField()),
                ('cofins_check', models.FloatField()),
                ('cofins_darf', models.FloatField()),
                ('cofins_dif_darf_recolher', models.FloatField()),
                ('cofins_contabilizar', models.FloatField()),
                ('cofins', models.FloatField()),
            ],
            options={
                'db_table': 'basecalculopiscofins',
            },
        ),
        migrations.CreateModel(
            name='ContaBaseCalculoIRPJCSLL',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('conta', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'contabasecalculoirpjcsll',
            },
        ),
        migrations.CreateModel(
            name='ContaBaseCalculoPisCofins',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('conta', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'contabasecalculopiscofins',
            },
        ),
        migrations.CreateModel(
            name='RelatorioRecuperados',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('data_entrada', models.DateField(auto_now_add=True)),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('soma_mes_ind', models.FloatField()),
            ],
            options={
                'db_table': 'relatoriorecuperados',
            },
        ),
        migrations.CreateModel(
            name='RelatorioSalvadosVendidos',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('data_entrada', models.DateField(auto_now_add=True)),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('soma_positivo_receita_baixa', models.FloatField()),
            ],
            options={
                'db_table': 'relatoriosalvend',
            },
        ),
        migrations.CreateModel(
            name='RelatorioSINPAG',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('data_entrada', models.DateField(auto_now_add=True)),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('soma_vr_mov', models.FloatField()),
                ('soma_vr_cos_ced', models.FloatField()),
                ('dif_soma_cos_ced_vr_mov', models.FloatField()),
            ],
            options={
                'db_table': 'relatoriosinpag',
            },
        ),
        migrations.CreateModel(
            name='RelatorioSINPAGAC',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('data_entrada', models.DateField(auto_now_add=True)),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('soma_vr_mov', models.FloatField()),
            ],
            options={
                'db_table': 'relatoriosinpagac',
            },
        ),
        migrations.CreateModel(
            name='UsuarioModel',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoSINPAGAC',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('vr_mov', models.FloatField()),
                ('cod_cia', models.CharField(max_length=255)),
                ('dt_base', models.CharField(max_length=255)),
                ('cod_coss', models.CharField(max_length=255)),
                ('num_sin', models.CharField(max_length=255)),
                ('num_apol', models.CharField(max_length=255)),
                ('g_cpf_bnf', models.CharField(max_length=255)),
                ('relatorio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='ibs.relatoriosinpagac')),
            ],
            options={
                'db_table': 'movimentacaosinpagac',
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoSINPAG',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('num_sin', models.CharField(max_length=255)),
                ('cpf_ben', models.CharField(max_length=255)),
                ('dt_base', models.CharField(max_length=255)),
                ('num_apol', models.CharField(max_length=255)),
                ('cod_ramo', models.CharField(max_length=255)),
                ('cod_cia', models.CharField(max_length=255)),
                ('vr_mov', models.FloatField(max_length=255)),
                ('vr_cos_ced', models.FloatField()),
                ('relatorio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='ibs.relatoriosinpag')),
            ],
            options={
                'db_table': 'movimentacaosinpag',
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoSalvadosVendidos',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('cod_cia', models.CharField(max_length=255)),
                ('dt_base', models.CharField(max_length=255)),
                ('cod_ctabal', models.CharField(max_length=255)),
                ('cod_classe', models.CharField(max_length=255)),
                ('receita_baixa', models.FloatField()),
                ('bx_dep_prej', models.FloatField()),
                ('bx_val_cont_ganho', models.FloatField()),
                ('relatorio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='ibs.relatoriosalvadosvendidos')),
            ],
            options={
                'db_table': 'movimentacaosalvend',
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoRecuperados',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('cod_cia', models.CharField(max_length=255)),
                ('num_sin', models.CharField(max_length=255)),
                ('cod_ramo', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('mes_ind', models.FloatField()),
                ('dt_base', models.CharField(max_length=255)),
                ('baixa_total', models.FloatField()),
                ('cod_prod', models.CharField(max_length=255)),
                ('relatorio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='ibs.relatoriorecuperados')),
            ],
            options={
                'db_table': 'movimentacaorecuperados',
            },
        ),
        migrations.CreateModel(
            name='ContaBalancete',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('conta_do_razao', models.CharField(max_length=255)),
                ('periodo', models.CharField(max_length=255)),
                ('saldo_anterior', models.FloatField()),
                ('debitos', models.FloatField()),
                ('creditos', models.FloatField()),
                ('movimento', models.FloatField()),
                ('saldo_acumulado', models.FloatField()),
                ('balancete', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ibs.balancete')),
            ],
            options={
                'db_table': 'contabalancete',
            },
        ),
    ]
