# Generated by Django 3.2.25 on 2025-06-20 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioRecuperadosNovo',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('data_entrada', models.DateField(auto_now_add=True)),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('dif_soma_baixa_ind_res_salv', models.FloatField()),
                ('soma_baixa_ind', models.FloatField(default=0)),
                ('soma_baixa_res', models.FloatField(default=0)),
                ('soma_baixa_salv', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'relatoriorecuperadosnovo',
            },
        ),
        migrations.CreateModel(
            name='RelatorioSalvadosVendidosNovos',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('data_entrada', models.DateField(auto_now_add=True)),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('soma_vr_mov', models.FloatField()),
            ],
            options={
                'db_table': 'relatoriosalvendnovos',
            },
        ),
        migrations.AddField(
            model_name='contabalancete',
            name='grupo_ramo',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contabalancete',
            name='nome_conta',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='movimentacaosinpag',
            name='tp_sin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movimentacaosinpagac',
            name='tp_sin',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='MovimentacaoSalvadosVendidosNovos',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('cod_cia', models.CharField(max_length=255)),
                ('dt_base', models.CharField(max_length=255)),
                ('tipo_mov', models.CharField(max_length=255)),
                ('cod_ramo', models.CharField(max_length=255)),
                ('cpf_ben', models.CharField(max_length=255)),
                ('num_sin', models.CharField(max_length=255)),
                ('vr_mov', models.FloatField(max_length=255)),
                ('tp_sin', models.IntegerField()),
                ('relatorio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='ibs.relatoriosalvadosvendidosnovos')),
            ],
            options={
                'db_table': 'movimentacaosalvendnovos',
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoRecuperadosNovo',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('cod_cia', models.CharField(max_length=255)),
                ('num_sin', models.CharField(max_length=255)),
                ('cod_ramo', models.CharField(max_length=255)),
                ('dt_base', models.CharField(max_length=255)),
                ('num_apol', models.CharField(max_length=255)),
                ('baixa_ind', models.FloatField(default=0, max_length=255)),
                ('baixa_salv', models.FloatField(default=0, max_length=255)),
                ('baixa_res', models.FloatField(default=0, max_length=255)),
                ('relatorio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='ibs.relatoriorecuperadosnovo')),
            ],
            options={
                'db_table': 'movimentacaorecuperadosnovo',
            },
        ),
    ]
