# Generated by Django 3.2.25 on 2025-08-07 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibs', '0002_auto_20250620_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='contabasecalculopiscofins',
            name='tipo_conta',
            field=models.IntegerField(choices=[(1, 'Credora'), (2, 'Devedora'), (3, 'Credora Devedora')], default=1),
        ),
        migrations.AddField(
            model_name='contabasecalculopiscofins',
            name='vigencia',
            field=models.BooleanField(default=True),
        ),
    ]
