# Generated by Django 3.2.25 on 2025-08-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibs', '0003_auto_20250807_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contabasecalculopiscofins',
            name='conta',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
