# Generated by Django 3.2.25 on 2025-08-28 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibs', '0004_alter_contabasecalculopiscofins_conta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimentacaorecuperadosnovo',
            old_name='cod_cia',
            new_name='tipo_sin',
        ),
        migrations.RemoveField(
            model_name='movimentacaorecuperadosnovo',
            name='dt_base',
        ),
        migrations.RemoveField(
            model_name='movimentacaorecuperadosnovo',
            name='num_apol',
        ),
    ]
