# Generated by Django 3.2.25 on 2025-09-01 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibs', '0005_auto_20250828_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariomodel',
            name='perfil',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('USUARIO', 'Usuario')], default='USUARIO', max_length=10),
        ),
    ]
