# Generated by Django 3.2.25 on 2025-09-03 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibs', '0006_usuariomodel_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariomodel',
            name='trocou_senha',
            field=models.BooleanField(default=False),
        ),
    ]
