# Generated by Django 3.2.25 on 2025-09-03 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibs', '0007_usuariomodel_trocou_senha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuariomodel',
            old_name='trocou_senha',
            new_name='precisa_trocar_senha',
        ),
    ]
