# Generated by Django 3.2.25 on 2025-09-30 15:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibs', '0008_rename_trocou_senha_usuariomodel_precisa_trocar_senha'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApuracaoPSL',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('ano', models.IntegerField(default=0)),
                ('mes', models.IntegerField(default=0)),
                ('total_base_calculo', models.FloatField(default=0)),
                ('total_pis_psl', models.FloatField(default=0)),
                ('total_cofins_psl', models.FloatField(default=0)),
                ('total_soma_pis_cofins', models.FloatField(default=0)),
                ('data_cadastro', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'apuracaopsl',
            },
        ),
        migrations.CreateModel(
            name='ContaBaseCalculoPSL',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('conta', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('vigencia', models.BooleanField(default=True)),
                ('tipo_conta', models.IntegerField(choices=[(1, 'Credora'), (2, 'Devedora'), (3, 'Credora Devedora')], default=3)),
            ],
            options={
                'db_table': 'contabasecalculopsl',
            },
        ),
        migrations.CreateModel(
            name='RamoAgrupadoPSL',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('ramo', models.CharField(max_length=100)),
                ('base_calculo', models.FloatField()),
                ('pis_psl', models.FloatField()),
                ('cofins_psl', models.FloatField()),
                ('total_soma_pis_cofins', models.FloatField()),
                ('apuracao_psl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ibs.apuracaopsl')),
            ],
            options={
                'db_table': 'ramoagrupadopsl',
            },
        ),
        migrations.CreateModel(
            name='ContaApuracaoPSL',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('conta', models.CharField(max_length=255)),
                ('descricao', models.CharField(default='', max_length=255)),
                ('apuracao_psl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ibs.apuracaopsl')),
            ],
            options={
                'db_table': 'contaapuracaopsl',
            },
        ),
    ]
