# Generated by Django 3.2.25 on 2025-11-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibs', '0009_apuracaopsl_contaapuracaopsl_contabasecalculopsl_ramoagrupadopsl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contabasecalculopsl',
            name='conta',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
