# Generated by Django 3.2.25 on 2025-12-22 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibs', '0010_alter_contabasecalculopsl_conta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApuracaoPisCofins',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('soma_receita_balancete', models.FloatField()),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('ano', models.IntegerField(default=0)),
                ('mes', models.IntegerField(default=0)),
                ('pis_retido', models.FloatField(default=0)),
                ('compensacao_pis', models.FloatField(default=0)),
                ('pis_recolher', models.FloatField()),
                ('pis_darf', models.FloatField()),
                ('pis', models.FloatField()),
                ('cofins_retido', models.FloatField(default=0)),
                ('compensacao_cofins', models.FloatField(default=0)),
                ('cofins_recolher', models.FloatField()),
                ('cofins_darf', models.FloatField()),
                ('cofins', models.FloatField()),
                ('relatorio_recuperados', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ibs.relatoriorecuperadosnovo')),
                ('relatorio_salvados_vendidos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ibs.relatoriosalvadosvendidosnovos')),
                ('relatorio_sinpag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ibs.relatoriosinpag')),
                ('relatorio_sinpagac', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ibs.relatoriosinpagac')),
            ],
            options={
                'db_table': 'apuracaopiscofins',
            },
        ),
        migrations.CreateModel(
            name='ApuracaoPisCofinsAPR',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('ano', models.IntegerField(default=0)),
                ('mes', models.IntegerField(default=0)),
                ('relatorio_recuperados', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ibs.relatoriorecuperadosnovo')),
                ('relatorio_salvados_vendidos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ibs.relatoriosalvadosvendidosnovos')),
                ('relatorio_sinpag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ibs.relatoriosinpag')),
                ('relatorio_sinpagac', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ibs.relatoriosinpagac')),
            ],
            options={
                'db_table': 'apuracaopiscofinsapr',
            },
        ),
        migrations.CreateModel(
            name='ContaApuracaoPisCofins',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('conta', models.CharField(max_length=255)),
                ('descricao', models.CharField(default='', max_length=255)),
                ('soma_movimento', models.FloatField()),
                ('apuracao_pis_cofins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ibs.apuracaopiscofins')),
            ],
            options={
                'db_table': 'contapuracaopiscofins',
            },
        ),
        migrations.CreateModel(
            name='ContaApuracaoPisCofinsAPR',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('conta', models.CharField(max_length=255)),
                ('descricao', models.CharField(default='', max_length=255)),
                ('apuracao_piscofins_apr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ibs.apuracaopiscofinsapr')),
            ],
            options={
                'db_table': 'contaapuracaopiscofinsapr',
            },
        ),
        migrations.CreateModel(
            name='RamoAgrupadoPisCofinsAPR',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('ramo', models.CharField(max_length=100)),
                ('receita', models.FloatField(default=0)),
                ('base_calculo', models.FloatField()),
                ('pis_apr', models.FloatField()),
                ('cofins_apr', models.FloatField()),
                ('apuracao_piscofins_apr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ibs.apuracaopiscofinsapr')),
            ],
            options={
                'db_table': 'ramoagrupadopiscofinsapr',
            },
        ),
        migrations.CreateModel(
            name='RamoAgrupadoPisCofinsRelatorioRecuperados',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('ramo', models.CharField(max_length=100)),
                ('soma_baixa_ind', models.FloatField(default=0)),
                ('soma_baixa_res', models.FloatField(default=0)),
                ('soma_baixa_salv', models.FloatField(default=0)),
                ('dif_soma_baixa_ind_res_salv', models.FloatField(default=0)),
                ('tipo_sin', models.CharField(max_length=100)),
                ('apuracao_piscofins_apr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ramos_recuperados', to='ibs.apuracaopiscofinsapr')),
            ],
            options={
                'db_table': 'ramoagrupadopiscofinsrelatoriorecuperados',
            },
        ),
        migrations.CreateModel(
            name='RamoAgrupadoPisCofinsRelatorioSalvadosVendidos',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('ramo', models.CharField(max_length=100)),
                ('soma_vr_mov', models.FloatField(default=0)),
                ('tipo_mov', models.IntegerField()),
                ('apuracao_piscofins_apr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ramos_salvadosvendidos', to='ibs.apuracaopiscofinsapr')),
            ],
            options={
                'db_table': 'ramoagrupadopiscofinsrelatoriosalvadosvendidos',
            },
        ),
        migrations.CreateModel(
            name='RamoAgrupadoPisCofinsRelatorioSinpag',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('ramo', models.CharField(max_length=100)),
                ('soma_vr_mov', models.FloatField(default=0)),
                ('soma_vr_cos_ced', models.FloatField()),
                ('dif_soma_vr_mod_cos_ced', models.FloatField(default=0)),
                ('tp_sin', models.IntegerField()),
                ('apuracao_piscofins_apr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ramos_sinpag', to='ibs.apuracaopiscofinsapr')),
            ],
            options={
                'db_table': 'ramoagrupadopiscofinsrelatoriosinpag',
            },
        ),
        migrations.CreateModel(
            name='RamoAgrupadoPisCofinsRelatorioSinpagac',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('ramo', models.CharField(max_length=100)),
                ('soma_vr_mov', models.FloatField(default=0)),
                ('tp_sin', models.IntegerField()),
                ('apuracao_piscofins_apr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ramos_sinpagac', to='ibs.apuracaopiscofinsapr')),
            ],
            options={
                'db_table': 'ramoagrupadopiscofinsrelatoriosinpagac',
            },
        ),
        migrations.DeleteModel(
            name='BaseCalculoPisCofins',
        ),
        migrations.AddField(
            model_name='movimentacaorecuperadosnovo',
            name='cod_ramo_susep',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='movimentacaosinpagac',
            name='cod_ramo',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='apuracaopsl',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
